### ISSUE TITLE
Fix event dispatching inconsistencies

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomla-platform#164]
Cherry pick the changes from joomla/joomla-cms#4308

**Comment by amazeika** [comment]
@johanjanssens I've just merged the events patch. Tested with Joomla catcher package and everything seems good.

**Comment by johanjanssens** [comment]
@amazeika  Please revert and create a feature branch and a PR. The branch can be created in the same repo. For guidelines see : https://github.com/joomlatools/joomla-platform/blob/master/CONTRIBUTING.md
